import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Brand
    'brand.name': 'Onnorokom',
    
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.contact': 'Contact',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Administration',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Hero Section
    'hero.title': 'Welcome to Onnorokom',
    'hero.subtitle': 'Building stronger communities through innovation and collaboration',
    'hero.description': 'Join our platform to connect, share, and grow together. Experience the power of community-driven solutions.',
    'hero.join.community': 'Join Our Community',
    'hero.learn.more': 'Learn More',
    
    // About Section
    'about.title': 'About Onnorokom',
    'about.subtitle': 'Empowering Communities Through Innovation',
    'about.description': 'Onnorokom is dedicated to creating meaningful connections and fostering collaboration within communities. Our platform provides tools and resources to help individuals and organizations work together towards common goals.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To build inclusive communities where everyone can contribute, learn, and thrive together.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'A world where technology bridges gaps and creates opportunities for all.',
    'about.values.title': 'Our Values',
    'about.values.description': 'Innovation, inclusivity, collaboration, and sustainable growth.',
    
    // Features Section
    'features.title': 'Key Features',
    'features.subtitle': 'Everything you need to build stronger communities',
    'features.community.title': 'Community Building',
    'features.community.description': 'Connect with like-minded individuals and build lasting relationships.',
    'features.collaboration.title': 'Collaboration Tools',
    'features.collaboration.description': 'Work together on projects with powerful collaboration features.',
    'features.resources.title': 'Resource Sharing',
    'features.resources.description': 'Share knowledge, tools, and resources with the community.',
    'features.events.title': 'Event Management',
    'features.events.description': 'Organize and participate in community events and activities.',
    'features.support.title': '24/7 Support',
    'features.support.description': 'Get help whenever you need it with our dedicated support team.',
    'features.analytics.title': 'Analytics & Insights',
    'features.analytics.description': 'Track progress and gain insights with comprehensive analytics.',
    
    // Members Section
    'members.title': 'Our Community',
    'members.subtitle': 'Meet some of our amazing community members',
    'members.john.bio': 'Community organizer passionate about bringing people together.',
    'members.sarah.bio': 'Tech enthusiast helping others learn and grow in technology.',
    'members.mike.bio': 'Environmental advocate working towards sustainable solutions.',
    'members.anna.bio': 'Education specialist focused on accessible learning opportunities.',
    
    // Contact Section
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'We\'d love to hear from you',
    'contact.description': 'Have questions or want to learn more about Onnorokom? Reach out to us and we\'ll get back to you as soon as possible.',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.phone': '+880 1234-567890',
    'contact.email.address': 'info@onnorokom.com',
    'contact.address': 'Dhaka, Bangladesh',
    
    // Footer
    'footer.description': 'Building stronger communities through innovation and collaboration.',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.news': 'News',
    'footer.press': 'Press',
    'footer.resources': 'Resources',
    'footer.blog': 'Blog',
    'footer.help': 'Help Center',
    'footer.guides': 'Guides',
    'footer.webinars': 'Webinars',
    'footer.community': 'Community',
    'footer.forums': 'Forums',
    'footer.events': 'Events',
    'footer.meetups': 'Meetups',
    'footer.newsletter': 'Newsletter',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.support': 'Support',
    'footer.administration': 'Administration',
    'footer.user.management': 'User Management',
    'footer.system.settings': 'System Settings',
    'footer.analytics': 'Analytics',
    'footer.reports': 'Reports',
    'footer.rights': '© 2023 Onnorokom. All rights reserved.',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personal.info': 'Personal Information',
    'profile.account.info': 'Account Information',
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.join.date': 'Join Date',
    'profile.last.login': 'Last Login',
    'profile.not.provided': 'Not provided',
    'profile.update.success.title': 'Profile Updated',
    'profile.update.success.message': 'Your profile has been updated successfully.',
    'profile.login.required': 'Login Required',
    'profile.login.message': 'Please log in to view your profile.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to your dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.stats.title': 'Statistics',
    'dashboard.total.users': 'Total Users',
    'dashboard.active.users': 'Active Users',
    'dashboard.new.registrations': 'New Registrations',
    'dashboard.pending.approvals': 'Pending Approvals',
    
    // Admin
    'admin.title': 'Administration',
    'admin.user.management': 'User Management',
    'admin.create.user': 'Create User',
    'admin.create.new.user': 'Create New User',
    'admin.search.users': 'Search users...',
    'admin.all.roles': 'All Roles',
    'admin.role.admin': 'Admin',
    'admin.role.moderator': 'Moderator',
    'admin.role.user': 'User',
    'admin.table.user': 'User',
    'admin.table.role': 'Role',
    'admin.table.status': 'Status',
    'admin.table.last.login': 'Last Login',
    'admin.table.actions': 'Actions',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.success': 'Success',
    'admin.error': 'Error',
    'admin.fill.required.fields': 'Please fill in all required fields.',
    'admin.user.created.successfully': 'User created successfully.',
    'admin.user.updated.successfully': 'User updated successfully.',
    'admin.user.deleted.successfully': 'User deleted successfully.',
    'admin.cannot.delete.yourself': 'You cannot delete your own account.',
    'admin.access.denied': 'Access Denied',
    'admin.insufficient.permissions': 'You do not have sufficient permissions to access this page.',
    'admin.login.required': 'Admin Access Required',
    'admin.login.message': 'Please log in with admin credentials to access this page.',
    
    // Login
    'login.title': 'Login',
    'login.welcome': 'Welcome back',
    'login.subtitle': 'Please sign in to your account',
    'login.email.placeholder': 'Enter your email',
    'login.password.placeholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot.password': 'Forgot password?',
    'login.sign.in': 'Sign In',
    'login.no.account': 'Don\'t have an account?',
    'login.register': 'Register here',
    'login.success': 'Login successful!',
    'login.error': 'Invalid credentials. Please try again.',
    
    // Registration
    'registration.step1.title': 'Phone Verification',
    'registration.step1.subtitle': 'Verify your phone number to get started',
    'registration.step2.title': 'Personal Information',
    'registration.step2.subtitle': 'Tell us about yourself',
    'registration.step3.title': 'Address Information',
    'registration.step3.subtitle': 'Where are you located?',
    'registration.step4.title': 'Professional Information',
    'registration.step4.subtitle': 'Share your professional background',
    'registration.phone.number': 'Phone Number',
    'registration.send.otp': 'Send OTP',
    'registration.enter.otp': 'Enter OTP',
    'registration.verify': 'Verify',
    'registration.password': 'Password',
    'registration.confirm.password': 'Confirm Password',
    'registration.full.name': 'Full Name',
    'registration.nick.names': 'Nick Names',
    'registration.nick.name': 'Nick Name',
    'registration.add.nickname': 'Add Nick Name',
    'registration.date.of.birth': 'Date of Birth',
    'registration.gender': 'Gender',
    'registration.select.gender': 'Select Gender',
    'registration.male': 'Male',
    'registration.female': 'Female',
    'registration.other': 'Other',
    'registration.religion': 'Religion',
    'registration.select.religion': 'Select Religion',
    'registration.islam': 'Islam',
    'registration.hinduism': 'Hinduism',
    'registration.christianity': 'Christianity',
    'registration.buddhism': 'Buddhism',
    'registration.marital.status': 'Marital Status',
    'registration.select.marital.status': 'Select Marital Status',
    'registration.single': 'Single',
    'registration.married': 'Married',
    'registration.divorced': 'Divorced',
    'registration.widowed': 'Widowed',
    'registration.emails': 'Email Addresses',
    'registration.email': 'Email',
    'registration.add.email': 'Add Email',
    'registration.additional.phones': 'Additional Phone Numbers',
    'registration.add.phone': 'Add Phone',
    'registration.personal': 'Personal',
    'registration.office': 'Office',
    'registration.present.address': 'Present Address',
    'registration.permanent.address': 'Permanent Address',
    'registration.district': 'District',
    'registration.select.district': 'Select District',
    'registration.address.details': 'Address Details',
    'registration.address.placeholder': 'Enter your full address...',
    'registration.professional.experience': 'Professional Experience',
    'registration.add.experience': 'Add Experience',
    'registration.experience': 'Experience',
    'registration.job.title': 'Job Title',
    'registration.company': 'Company',
    'registration.start.date': 'Start Date',
    'registration.end.date': 'End Date',
    'registration.currently.working': 'I am currently working in this role',
    'registration.job.location': 'Job Location',
    'registration.job.description': 'Job Description',
    'registration.job.description.placeholder': 'Describe your role and responsibilities...',
    'registration.profile.headline': 'Profile Headline',
    'registration.profile.headline.placeholder': 'A brief professional summary...',
    'registration.previous': 'Previous',
    'registration.next': 'Next',
    'registration.save.profile': 'Save Profile',
    'registration.otp.sent': 'OTP Sent',
    'registration.otp.message': 'Verification code sent to your phone. Use code: ',
    'registration.otp.verified': 'OTP Verified',
    'registration.otp.success': 'Phone number verified successfully!',
    'registration.otp.error': 'Verification Failed',
    'registration.otp.invalid': 'Invalid OTP. Please try again.',
    'registration.error': 'Error',
    'registration.complete.step1': 'Please complete phone verification and set a password.',
    'registration.password.mismatch': 'Passwords do not match.',
    'registration.name.required': 'Name is required.',
    'registration.district.required': 'District selection is required.',
    'registration.success': 'Registration Successful',
    'registration.profile.created': 'Your profile has been created successfully!',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred. Please try again.',
    'common.success': 'Operation completed successfully.',
  },
  bn: {
    // Brand
    'brand.name': 'অন্যরকম',
    
    // Navigation
    'nav.home': 'হোম',
    'nav.about': 'সম্পর্কে',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.contact': 'যোগাযোগ',
    'nav.profile': 'প্রোফাইল',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.admin': 'প্রশাসন',
    'nav.login': 'লগইন',
    'nav.logout': 'লগআউট',
    
    // Hero Section
    'hero.title': 'অন্যরকমে স্বাগতম',
    'hero.subtitle': 'উদ্ভাবন এবং সহযোগিতার মাধ্যমে শক্তিশালী সম্প্রদায় গড়ে তোলা',
    'hero.description': 'সংযোগ, ভাগাভাগি এবং একসাথে বেড়ে ওঠার জন্য আমাদের প্ল্যাটফর্মে যোগ দিন। সম্প্রদায়-চালিত সমাধানের শক্তি অনুভব করুন।',
    'hero.join.community': 'আমাদের সম্প্রদায়ে যোগ দিন',
    'hero.learn.more': 'আরো জানুন',
    
    // About Section
    'about.title': 'অন্যরকম সম্পর্কে',
    'about.subtitle': 'উদ্ভাবনের মাধ্যমে সম্প্রদায়কে ক্ষমতায়ন',
    'about.description': 'অন্যরকম অর্থপূর্ণ সংযোগ তৈরি এবং সম্প্রদায়ের মধ্যে সহযোগিতা বৃদ্ধিতে নিবেদিত। আমাদের প্ল্যাটফর্ম ব্যক্তি এবং সংস্থাগুলিকে সাধারণ লক্ষ্যের দিকে একসাথে কাজ করতে সাহায্য করার জন্য সরঞ্জাম এবং সংস্থান প্রদান করে।',
    'about.mission.title': 'আমাদের মিশন',
    'about.mission.description': 'অন্তর্ভুক্তিমূলক সম্প্রদায় গড়ে তোলা যেখানে সবাই অবদান রাখতে, শিখতে এবং একসাথে উন্নতি করতে পারে।',
    'about.vision.title': 'আমাদের দৃষ্টিভঙ্গি',
    'about.vision.description': 'এমন একটি বিশ্ব যেখানে প্রযুক্তি ফাঁক দূর করে এবং সবার জন্য সুযোগ সৃষ্টি করে।',
    'about.values.title': 'আমাদের মূল্যবোধ',
    'about.values.description': 'উদ্ভাবন, অন্তর্ভুক্তি, সহযোগিতা এবং টেকসই বৃদ্ধি।',
    
    // Features Section
    'features.title': 'মূল বৈশিষ্ট্য',
    'features.subtitle': 'শক্তিশালী সম্প্রদায় গড়তে আপনার যা প্রয়োজন সব কিছু',
    'features.community.title': 'সম্প্রদায় গঠন',
    'features.community.description': 'সমমনা ব্যক্তিদের সাথে সংযোগ করুন এবং দীর্ঘস্থায়ী সম্পর্ক গড়ুন।',
    'features.collaboration.title': 'সহযোগিতার সরঞ্জাম',
    'features.collaboration.description': 'শক্তিশালী সহযোগিতার বৈশিষ্ট্য দিয়ে প্রকল্পে একসাথে কাজ করুন।',
    'features.resources.title': 'সম্পদ ভাগাভাগি',
    'features.resources.description': 'সম্প্রদায়ের সাথে জ্ঞান, সরঞ্জাম এবং সম্পদ ভাগ করুন।',
    'features.events.title': 'ইভেন্ট ব্যবস্থাপনা',
    'features.events.description': 'সম্প্রদায়িক ইভেন্ট এবং কার্যক্রম সংগঠিত করুন এবং অংশগ্রহণ করুন।',
    'features.support.title': '২৪/৭ সহায়তা',
    'features.support.description': 'আমাদের নিবেদিত সহায়তা দলের সাথে যখনই প্রয়োজন সাহায্য পান।',
    'features.analytics.title': 'বিশ্লেষণ এবং অন্তর্দৃষ্টি',
    'features.analytics.description': 'ব্যাপক বিশ্লেষণের সাথে অগ্রগতি ট্র্যাক করুন এবং অন্তর্দৃষ্টি লাভ করুন।',
    
    // Members Section
    'members.title': 'আমাদের সম্প্রদায়',
    'members.subtitle': 'আমাদের কিছু আশ্চর্যজনক সম্প্রদায়ের সদস্যদের সাথে পরিচিত হন',
    'members.john.bio': 'মানুষদের একসাথে আনতে উৎসাহী সম্প্রদায় সংগঠক।',
    'members.sarah.bio': 'প্রযুক্তি উৎসাহী যিনি অন্যদের প্রযুক্তিতে শিখতে এবং বেড়ে উঠতে সাহায্য করেন।',
    'members.mike.bio': 'টেকসই সমাধানের দিকে কাজ করা পরিবেশ উকিল।',
    'members.anna.bio': 'অ্যাক্সেসযোগ্য শিক্ষার সুযোগের উপর দৃষ্টি নিবদ্ধ করা শিক্ষা বিশেষজ্ঞ।',
    
    // Contact Section
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'আমরা আপনার কাছ থেকে শুনতে চাই',
    'contact.description': 'প্রশ্ন আছে বা অন্যরকম সম্পর্কে আরও জানতে চান? আমাদের সাথে যোগাযোগ করুন এবং আমরা যত তাড়াতাড়ি সম্ভব আপনার কাছে ফিরে আসব।',
    'contact.name': 'পূর্ণ নাম',
    'contact.email': 'ইমেইল ঠিকানা',
    'contact.message': 'আপনার বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'contact.info.title': 'যোগাযোগের তথ্য',
    'contact.phone': '+৮৮০ ১২৩৪-৫৬৭৮৯০',
    'contact.email.address': 'info@onnorokom.com',
    'contact.address': 'ঢাকা, বাংলাদেশ',
    
    // Footer
    'footer.description': 'উদ্ভাবন এবং সহযোগিতার মাধ্যমে শক্তিশালী সম্প্রদায় গড়ে তোলা।',
    'footer.company': 'কোম্পানি',
    'footer.about': 'আমাদের সম্পর্কে',
    'footer.careers': 'ক্যারিয়ার',
    'footer.news': 'সংবাদ',
    'footer.press': 'প্রেস',
    'footer.resources': 'সম্পদ',
    'footer.blog': 'ব্লগ',
    'footer.help': 'সহায়তা কেন্দ্র',
    'footer.guides': 'গাইড',
    'footer.webinars': 'ওয়েবিনার',
    'footer.community': 'সম্প্রদায়',
    'footer.forums': 'ফোরাম',
    'footer.events': 'ইভেন্ট',
    'footer.meetups': 'মিটআপ',
    'footer.newsletter': 'নিউজলেটার',
    'footer.legal': 'আইনি',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'সেবার শর্তাবলী',
    'footer.cookies': 'কুকি নীতি',
    'footer.support': 'সহায়তা',
    'footer.administration': 'প্রশাসন',
    'footer.user.management': 'ব্যবহারকারী ব্যবস্থাপনা',
    'footer.system.settings': 'সিস্টেম সেটিংস',
    'footer.analytics': 'বিশ্লেষণ',
    'footer.reports': 'রিপোর্ট',
    'footer.rights': '© ২০২৩ অন্যরকম। সমস্ত অধিকার সংরক্ষিত।',
    
    // Profile
    'profile.title': 'প্রোফাইল',
    'profile.personal.info': 'ব্যক্তিগত তথ্য',
    'profile.account.info': 'অ্যাকাউন্টের তথ্য',
    'profile.edit': 'প্রোফাইল সম্পাদনা',
    'profile.name': 'নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন',
    'profile.address': 'ঠিকানা',
    'profile.join.date': 'যোগদানের তারিখ',
    'profile.last.login': 'শেষ লগইন',
    'profile.not.provided': 'প্রদান করা হয়নি',
    'profile.update.success.title': 'প্রোফাইল আপডেট হয়েছে',
    'profile.update.success.message': 'আপনার প্রোফাইল সফলভাবে আপডেট হয়েছে।',
    'profile.login.required': 'লগইন প্রয়োজন',
    'profile.login.message': 'আপনার প্রোফাইল দেখতে অনুগ্রহ করে লগইন করুন।',
    
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.welcome': 'আপনার ড্যাশবোর্ডে স্বাগতম',
    'dashboard.overview': 'সংক্ষিপ্ত বিবরণ',
    'dashboard.stats.title': 'পরিসংখ্যান',
    'dashboard.total.users': 'মোট ব্যবহারকারী',
    'dashboard.active.users': 'সক্রিয় ব্যবহারকারী',
    'dashboard.new.registrations': 'নতুন নিবন্ধন',
    'dashboard.pending.approvals': 'অনুমোদনের অপেক্ষায়',
    
    // Admin
    'admin.title': 'প্রশাসন',
    'admin.user.management': 'ব্যবহারকারী ব্যবস্থাপনা',
    'admin.create.user': 'ব্যবহারকারী তৈরি করুন',
    'admin.create.new.user': 'নতুন ব্যবহারকারী তৈরি করুন',
    'admin.search.users': 'ব্যবহারকারী খুঁজুন...',
    'admin.all.roles': 'সমস্ত ভূমিকা',
    'admin.role.admin': 'প্রশাসক',
    'admin.role.moderator': 'মডারেটর',
    'admin.role.user': 'ব্যবহারকারী',
    'admin.table.user': 'ব্যবহারকারী',
    'admin.table.role': 'ভূমিকা',
    'admin.table.status': 'অবস্থা',
    'admin.table.last.login': 'শেষ লগইন',
    'admin.table.actions': 'কার্যক্রম',
    'admin.status.active': 'সক্রিয়',
    'admin.status.inactive': 'নিষ্ক্রিয়',
    'admin.success': 'সফল',
    'admin.error': 'ত্রুটি',
    'admin.fill.required.fields': 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
    'admin.user.created.successfully': 'ব্যবহারকারী সফলভাবে তৈরি হয়েছে।',
    'admin.user.updated.successfully': 'ব্যবহারকারী সফলভাবে আপডেট হয়েছে।',
    'admin.user.deleted.successfully': 'ব্যবহারকারী সফলভাবে মুছে ফেলা হয়েছে।',
    'admin.cannot.delete.yourself': 'আপনি আপনার নিজের অ্যাকাউন্ট মুছতে পারবেন না।',
    'admin.access.denied': 'প্রবেশাধিকার অস্বীকৃত',
    'admin.insufficient.permissions': 'এই পৃষ্ঠায় প্রবেশের জন্য আপনার পর্যাপ্ত অনুমতি নেই।',
    'admin.login.required': 'প্রশাসক প্রবেশাধিকার প্রয়োজন',
    'admin.login.message': 'এই পৃষ্ঠায় প্রবেশের জন্য অনুগ্রহ করে প্রশাসক শংসাপত্র দিয়ে লগইন করুন।',
    
    // Login
    'login.title': 'লগইন',
    'login.welcome': 'ফিরে আসার জন্য স্বাগতম',
    'login.subtitle': 'অনুগ্রহ করে আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'login.email.placeholder': 'আপনার ইমেইল লিখুন',
    'login.password.placeholder': 'আপনার পাসওয়ার্ড লিখুন',
    'login.remember': 'আমাকে মনে রাখুন',
    'login.forgot.password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'login.sign.in': 'সাইন ইন',
    'login.no.account': 'কোনো অ্যাকাউন্ট নেই?',
    'login.register': 'এখানে নিবন্ধন করুন',
    'login.success': 'লগইন সফল!',
    'login.error': 'ভুল শংসাপত্র। অনুগ্রহ করে আবার চেষ্টা করুন।',
    
    // Registration
    'registration.step1.title': 'ফোন যাচাইকরণ',
    'registration.step1.subtitle': 'শুরু করতে আপনার ফোন নম্বর যাচাই করুন',
    'registration.step2.title': 'ব্যক্তিগত তথ্য',
    'registration.step2.subtitle': 'আপনার সম্পর্কে আমাদের বলুন',
    'registration.step3.title': 'ঠিকানার তথ্য',
    'registration.step3.subtitle': 'আপনি কোথায় অবস্থিত?',
    'registration.step4.title': 'পেশাগত তথ্য',
    'registration.step4.subtitle': 'আপনার পেশাগত পটভূমি শেয়ার করুন',
    'registration.phone.number': 'ফোন নম্বর',
    'registration.send.otp': 'OTP পাঠান',
    'registration.enter.otp': 'OTP লিখুন',
    'registration.verify': 'যাচাই করুন',
    'registration.password': 'পাসওয়ার্ড',
    'registration.confirm.password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'registration.full.name': 'পূর্ণ নাম',
    'registration.nick.names': 'ডাক নাম',
    'registration.nick.name': 'ডাক নাম',
    'registration.add.nickname': 'ডাক নাম যোগ করুন',
    'registration.date.of.birth': 'জন্ম তারিখ',
    'registration.gender': 'লিঙ্গ',
    'registration.select.gender': 'লিঙ্গ নির্বাচন করুন',
    'registration.male': 'পুরুষ',
    'registration.female': 'মহিলা',
    'registration.other': 'অন্যান্য',
    'registration.religion': 'ধর্ম',
    'registration.select.religion': 'ধর্ম নির্বাচন করুন',
    'registration.islam': 'ইসলাম',
    'registration.hinduism': 'হিন্দু ধর্ম',
    'registration.christianity': 'খ্রিস্টান ধর্ম',
    'registration.buddhism': 'বৌদ্ধ ধর্ম',
    'registration.marital.status': 'বৈবাহিক অবস্থা',
    'registration.select.marital.status': 'বৈবাহিক অবস্থা নির্বাচন করুন',
    'registration.single': 'অবিবাহিত',
    'registration.married': 'বিবাহিত',
    'registration.divorced': 'তালাকপ্রাপ্ত',
    'registration.widowed': 'বিধবা/বিপত্নীক',
    'registration.emails': 'ইমেইল ঠিকানা',
    'registration.email': 'ইমেইল',
    'registration.add.email': 'ইমেইল যোগ করুন',
    'registration.additional.phones': 'অতিরিক্ত ফোন নম্বর',
    'registration.add.phone': 'ফোন যোগ করুন',
    'registration.personal': 'ব্যক্তিগত',
    'registration.office': 'অফিস',
    'registration.present.address': 'বর্তমান ঠিকানা',
    'registration.permanent.address': 'স্থায়ী ঠিকানা',
    'registration.district': 'জেলা',
    'registration.select.district': 'জেলা নির্বাচন করুন',
    'registration.address.details': 'ঠিকানার বিবরণ',
    'registration.address.placeholder': 'আপনার সম্পূর্ণ ঠিকানা লিখুন...',
    'registration.professional.experience': 'পেশাগত অভিজ্ঞতা',
    'registration.add.experience': 'অভিজ্ঞতা যোগ করুন',
    'registration.experience': 'অভিজ্ঞতা',
    'registration.job.title': 'চাকরির পদবী',
    'registration.company': 'কোম্পানি',
    'registration.start.date': 'শুরুর তারিখ',
    'registration.end.date': 'শেষের তারিখ',
    'registration.currently.working': 'আমি বর্তমানে এই ভূমিকায় কাজ করছি',
    'registration.job.location': 'চাকরির স্থান',
    'registration.job.description': 'চাকরির বিবরণ',
    'registration.job.description.placeholder': 'আপনার ভূমিকা এবং দায়িত্ব বর্ণনা করুন...',
    'registration.profile.headline': 'প্রোফাইল শিরোনাম',
    'registration.profile.headline.placeholder': 'একটি সংক্ষিপ্ত পেশাদার সারসংক্ষেপ...',
    'registration.previous': 'পূর্ববর্তী',
    'registration.next': 'পরবর্তী',
    'registration.save.profile': 'প্রোফাইল সংরক্ষণ করুন',
    'registration.otp.sent': 'OTP পাঠানো হয়েছে',
    'registration.otp.message': 'আপনার ফোনে যাচাইকরণ কোড পাঠানো হয়েছে। কোড ব্যবহার করুন: ',
    'registration.otp.verified': 'OTP যাচাই হয়েছে',
    'registration.otp.success': 'ফোন নম্বর সফলভাবে যাচাই হয়েছে!',
    'registration.otp.error': 'যাচাইকরণ ব্যর্থ',
    'registration.otp.invalid': 'ভুল OTP। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'registration.error': 'ত্রুটি',
    'registration.complete.step1': 'অনুগ্রহ করে ফোন যাচাইকরণ সম্পূর্ণ করুন এবং একটি পাসওয়ার্ড সেট করুন।',
    'registration.password.mismatch': 'পাসওয়ার্ড মিলছে না।',
    'registration.name.required': 'নাম প্রয়োজন।',
    'registration.district.required': 'জেলা নির্বাচন প্রয়োজন।',
    'registration.success': 'নিবন্ধন সফল',
    'registration.profile.created': 'আপনার প্রোফাইল সফলভাবে তৈরি হয়েছে!',
    
    // Common
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.edit': 'সম্পাদনা',
    'common.delete': 'মুছুন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'common.success': 'অপারেশন সফলভাবে সম্পন্ন হয়েছে।',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bn' : 'en');
  };

  const t = (key: string): string => {
    try {
      return translations[language][key] || key;
    } catch (Error) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{
      language,
      toggleLanguage,
      t
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
