
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Brand
    'brand.name': 'Onnorokom',
    
    // Navigation
    'nav.home': 'Home',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Administration',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Hero Section
    'hero.welcome': 'Welcome to',
    'hero.community': 'Onnorokom Community',
    'hero.description': 'Connect, collaborate, and grow with like-minded individuals in our vibrant community platform.',
    'hero.join': 'Join Our Community',
    'hero.learn': 'Learn More',
    'hero.members': 'Members',
    'hero.connections': 'Connections',
    'hero.satisfaction': 'Satisfaction',
    'hero.overview': 'Community Overview',
    'hero.discover': 'Discover what makes us special',
    
    // Features
    'features.title': 'Why Choose Onnorokom?',
    'features.subtitle': 'Discover the features that make our community special',
    'features.networking.title': 'Professional Networking',
    'features.networking.description': 'Connect with professionals across Bangladesh and build meaningful relationships.',
    'features.events.title': 'Community Events',
    'features.events.description': 'Join exclusive events, workshops, and meetups to enhance your skills.',
    'features.support.title': '24/7 Support',
    'features.support.description': 'Get help whenever you need it with our dedicated support team.',
    'features.growth.title': 'Career Growth',
    'features.growth.description': 'Access resources and opportunities to advance your professional journey.',
    
    // About
    'about.title': 'About Onnorokom',
    'about.subtitle': 'Building bridges across Bangladesh',
    'about.description': 'Onnorokom is more than just a community platform. We are dedicated to fostering connections, promoting collaboration, and empowering individuals across Bangladesh to achieve their personal and professional goals.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To create an inclusive digital space where every individual can connect, learn, and grow together.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To be the leading community platform that bridges geographical and cultural gaps across Bangladesh.',
    'about.values.title': 'Our Values',
    'about.values.description': 'We believe in inclusivity, authenticity, collaboration, and continuous learning.',
    
    // Members
    'members.title': 'Meet Our Community',
    'members.subtitle': 'Connect with amazing people from all walks of life',
    'members.join': 'Join 10,000+ Members',
    'members.professionals': 'Professionals',
    'members.students': 'Students',
    'members.entrepreneurs': 'Entrepreneurs',
    
    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'We would love to hear from you',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Dhaka, Bangladesh',
    'contact.info.phone': '+880 1234-567890',
    'contact.info.email': 'contact@onnorokom.com',
    'contact.follow': 'Follow Us',
    
    // Footer
    'footer.description': 'Building connections and fostering growth across Bangladesh.',
    'footer.quick.links': 'Quick Links',
    'footer.community': 'Community',
    'footer.support': 'Support',
    'footer.resources': 'Resources',
    'footer.events': 'Events',
    'footer.blog': 'Blog',
    'footer.help': 'Help Center',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    'footer.social': 'Follow us on social media',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin': 'Sign In',
    'login.signup': 'Don\'t have an account? Sign up',
    'login.demo': 'Demo Accounts',
    'login.admin': 'Admin Login',
    'login.moderator': 'Moderator Login',
    'login.user': 'User Login',
    'login.error': 'Invalid email or password',
    'login.success': 'Login successful',
    
    // Profile
    'profile.personal.info': 'Personal Information',
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.not.provided': 'Not provided',
    'profile.account.info': 'Account Information',
    'profile.join.date': 'Join Date',
    'profile.last.login': 'Last Login',
    'profile.update.success.title': 'Profile Updated',
    'profile.update.success.message': 'Your profile has been updated successfully.',
    'profile.login.required': 'Login Required',
    'profile.login.message': 'Please login to access your profile.',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.welcome.message': 'Here\'s an overview of your community dashboard.',
    'dashboard.stats.total.users': 'Total Users',
    'dashboard.stats.active.users': 'Active Users',
    'dashboard.stats.recent.logins': 'Recent Logins',
    'dashboard.stats.administrators': 'Administrators',
    'dashboard.role.distribution': 'Role Distribution',
    'dashboard.quick.actions': 'Quick Actions',
    'dashboard.action.manage.users': 'Manage Users',
    'dashboard.action.view.activity': 'View Activity',
    'dashboard.action.security.settings': 'Security Settings',
    'dashboard.login.required': 'Dashboard Access Required',
    'dashboard.login.message': 'Please login to access the dashboard.',
    
    // Admin
    'admin.user.management': 'User Management',
    'admin.create.user': 'Create User',
    'admin.search.users': 'Search users...',
    'admin.all.roles': 'All Roles',
    'admin.role.admin': 'Admin',
    'admin.role.moderator': 'Moderator',
    'admin.role.user': 'User',
    'admin.create.new.user': 'Create New User',
    'admin.table.user': 'User',
    'admin.table.role': 'Role',
    'admin.table.status': 'Status',
    'admin.table.last.login': 'Last Login',
    'admin.table.actions': 'Actions',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.error': 'Error',
    'admin.success': 'Success',
    'admin.fill.required.fields': 'Please fill in all required fields.',
    'admin.user.created.successfully': 'User created successfully.',
    'admin.user.updated.successfully': 'User updated successfully.',
    'admin.user.deleted.successfully': 'User deleted successfully.',
    'admin.cannot.delete.yourself': 'You cannot delete your own account.',
    'admin.access.denied': 'Access Denied',
    'admin.insufficient.permissions': 'You do not have sufficient permissions to access this page.',
    'admin.login.required': 'Admin Access Required',
    'admin.login.message': 'Please login with admin privileges to access administration.',
    
    // Registration
    'registration.step1.title': 'Phone & Security',
    'registration.step1.subtitle': 'Verify your phone number and set up security',
    'registration.step2.title': 'Personal Information',
    'registration.step2.subtitle': 'Tell us about yourself',
    'registration.step3.title': 'Address Information',
    'registration.step3.subtitle': 'Where are you located?',
    'registration.step4.title': 'Professional Information',
    'registration.step4.subtitle': 'Share your professional background',
    'registration.phone.number': 'Phone Number',
    'registration.send.otp': 'Send OTP',
    'registration.enter.otp': 'Enter OTP',
    'registration.verify': 'Verify',
    'registration.password': 'Password',
    'registration.confirm.password': 'Confirm Password',
    'registration.full.name': 'Full Name',
    'registration.nick.names': 'Nick Names',
    'registration.nick.name': 'Nick Name',
    'registration.add.nickname': 'Add Nick Name',
    'registration.date.of.birth': 'Date of Birth',
    'registration.gender': 'Gender',
    'registration.select.gender': 'Select Gender',
    'registration.male': 'Male',
    'registration.female': 'Female',
    'registration.other': 'Other',
    'registration.religion': 'Religion',
    'registration.select.religion': 'Select Religion',
    'registration.islam': 'Islam',
    'registration.hinduism': 'Hinduism',
    'registration.christianity': 'Christianity',
    'registration.buddhism': 'Buddhism',
    'registration.marital.status': 'Marital Status',
    'registration.select.marital.status': 'Select Marital Status',
    'registration.single': 'Single',
    'registration.married': 'Married',
    'registration.divorced': 'Divorced',
    'registration.widowed': 'Widowed',
    'registration.emails': 'Email Addresses',
    'registration.email': 'Email',
    'registration.add.email': 'Add Email',
    'registration.additional.phones': 'Additional Phone Numbers',
    'registration.add.phone': 'Add Phone',
    'registration.personal': 'Personal',
    'registration.office': 'Office',
    'registration.present.address': 'Present Address',
    'registration.permanent.address': 'Permanent Address',
    'registration.district': 'District',
    'registration.select.district': 'Select District',
    'registration.address.details': 'Address Details',
    'registration.address.placeholder': 'Village, House, Road...',
    'registration.profile.headline': 'Profile Headline',
    'registration.profile.headline.placeholder': 'Brief description about yourself...',
    'registration.professional.experience': 'Professional Experience',
    'registration.add.experience': 'Add Experience',
    'registration.experience': 'Experience',
    'registration.job.title': 'Job Title',
    'registration.company': 'Company/Organization',
    'registration.start.date': 'Start Date',
    'registration.end.date': 'End Date',
    'registration.currently.working': 'I am currently working in this role',
    'registration.job.location': 'Job Location',
    'registration.job.description': 'Job Description',
    'registration.job.description.placeholder': 'Describe your role and responsibilities...',
    'registration.next': 'Next',
    'registration.previous': 'Previous',
    'registration.save.profile': 'Save & Go to Profile',
    'registration.error': 'Registration Error',
    'registration.complete.step1': 'Please complete phone verification and set password.',
    'registration.password.mismatch': 'Passwords do not match.',
    'registration.name.required': 'Full name is required.',
    'registration.district.required': 'District selection is required for both addresses.',
    'registration.otp.sent': 'OTP Sent',
    'registration.otp.message': 'OTP sent to your phone. Demo OTP:',
    'registration.otp.verified': 'OTP Verified',
    'registration.otp.success': 'Phone number verified successfully.',
    'registration.otp.error': 'Verification Failed',
    'registration.otp.invalid': 'Invalid OTP. Please try again.',
    'registration.success': 'Registration Successful',
    'registration.profile.created': 'Your profile has been created successfully.',
    'registration.title': 'Join Our Community'
  },
  bn: {
    // Brand
    'brand.name': 'অন্যরকম',
    
    // Navigation
    'nav.home': 'হোম',
    'nav.profile': 'প্রোফাইল',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.admin': 'প্রশাসন',
    'nav.login': 'লগইন',
    'nav.logout': 'লগআউট',
    
    // Hero Section
    'hero.welcome': 'স্বাগতম',
    'hero.community': 'অন্যরকম কমিউনিটিতে',
    'hero.description': 'আমাদের প্রাণবন্ত কমিউনিটি প্ল্যাটফর্মে সমমনা ব্যক্তিদের সাথে যুক্ত হন, সহযোগিতা করুন এবং এগিয়ে চলুন।',
    'hero.join': 'আমাদের কমিউনিটিতে যোগ দিন',
    'hero.learn': 'আরও জানুন',
    'hero.members': 'সদস্য',
    'hero.connections': 'সংযোগ',
    'hero.satisfaction': 'সন্তুষ্টি',
    'hero.overview': 'কমিউনিটি ওভারভিউ',
    'hero.discover': 'আমাদের বিশেষত্ব আবিষ্কার করুন',
    
    // Features
    'features.title': 'কেন অন্যরকম বেছে নেবেন?',
    'features.subtitle': 'আমাদের কমিউনিটিকে বিশেষ করে তোলে এমন বৈশিষ্ট্যগুলি আবিষ্কার করুন',
    'features.networking.title': 'পেশাদার নেটওয়ার্কিং',
    'features.networking.description': 'বাংলাদেশের পেশাদারদের সাথে সংযুক্ত হন এবং অর্থবহ সম্পর্ক গড়ুন।',
    'features.events.title': 'কমিউনিটি ইভেন্ট',
    'features.events.description': 'আপনার দক্ষতা বৃদ্ধির জন্য একচেটিয়া ইভেন্ট, কর্মশালা এবং মিটআপে যোগ দিন।',
    'features.support.title': '২৪/৭ সাপোর্ট',
    'features.support.description': 'আমাদের নিবেদিতপ্রাণ সাপোর্ট টিমের সাথে যখনই প্রয়োজন সাহায্য পান।',
    'features.growth.title': 'ক্যারিয়ার বৃদ্ধি',
    'features.growth.description': 'আপনার পেশাগত যাত্রাকে এগিয়ে নিতে সম্পদ এবং সুযোগ অ্যাক্সেস করুন।',
    
    // About
    'about.title': 'অন্যরকম সম্পর্কে',
    'about.subtitle': 'বাংলাদেশ জুড়ে সেতুবন্ধন তৈরি',
    'about.description': 'অন্যরকম শুধুমাত্র একটি কমিউনিটি প্ল্যাটফর্ম নয়। আমরা সংযোগ স্থাপন, সহযোগিতা প্রচার এবং বাংলাদেশের ব্যক্তিদের তাদের ব্যক্তিগত ও পেশাগত লক্ষ্য অর্জনে ক্ষমতায়নের জন্য নিবেদিত।',
    'about.mission.title': 'আমাদের মিশন',
    'about.mission.description': 'একটি অন্তর্ভুক্তিমূলক ডিজিটাল স্থান তৈরি করা যেখানে প্রতিটি ব্যক্তি সংযুক্ত হতে, শিখতে এবং একসাথে বেড়ে উঠতে পারে।',
    'about.vision.title': 'আমাদের দৃষ্টিভঙ্গি',
    'about.vision.description': 'বাংলাদেশের ভৌগোলিক ও সাংস্কৃতিক ব্যবধান দূর করে এমন নেতৃস্থানীয় কমিউনিটি প্ল্যাটফর্ম হওয়া।',
    'about.values.title': 'আমাদের মূল্যবোধ',
    'about.values.description': 'আমরা অন্তর্ভুক্তি, সত্যতা, সহযোগিতা এবং ক্রমাগত শেখায় বিশ্বাস করি।',
    
    // Members
    'members.title': 'আমাদের কমিউনিটির সাথে পরিচিত হন',
    'members.subtitle': 'জীবনের সকল ক্ষেত্রের আশ্চর্য মানুষদের সাথে সংযুক্ত হন',
    'members.join': '১০,০০০+ সদস্যের সাথে যোগ দিন',
    'members.professionals': 'পেশাদার',
    'members.students': 'শিক্ষার্থী',
    'members.entrepreneurs': 'উদ্যোক্তা',
    
    // Contact
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'আমরা আপনার কথা শুনতে ভালোবাসি',
    'contact.name': 'পূর্ণ নাম',
    'contact.email': 'ইমেইল ঠিকানা',
    'contact.subject': 'বিষয়',
    'contact.message': 'বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'contact.info.title': 'যোগাযোগের তথ্য',
    'contact.info.address': 'ঢাকা, বাংলাদেশ',
    'contact.info.phone': '+৮৮০ ১২৩৪-৫৬৭৮৯০',
    'contact.info.email': 'contact@onnorokom.com',
    'contact.follow': 'আমাদের ফলো করুন',
    
    // Footer
    'footer.description': 'বাংলাদেশ জুড়ে সংযোগ স্থাপন এবং উন্নতি সাধন।',
    'footer.quick.links': 'দ্রুত লিংক',
    'footer.community': 'কমিউনিটি',
    'footer.support': 'সাপোর্ট',
    'footer.resources': 'রিসোর্স',
    'footer.events': 'ইভেন্ট',
    'footer.blog': 'ব্লগ',
    'footer.help': 'সাহায্য কেন্দ্র',
    'footer.faq': 'প্রশ্নোত্তর',
    'footer.contact': 'যোগাযোগ',
    'footer.privacy': 'গোপনীয়তার নীতি',
    'footer.terms': 'সেবার শর্তাবলী',
    'footer.rights': 'সকল অধিকার সংরক্ষিত।',
    'footer.social': 'সোশ্যাল মিডিয়ায় আমাদের ফলো করুন',
    
    // Common
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.edit': 'সম্পাদনা',
    'common.delete': 'মুছুন',
    'common.back': 'পিছনে',
    'common.next': 'পরবর্তী',
    'common.previous': 'পূর্ববর্তী',
    'common.submit': 'জমা দিন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফল',
    
    // Login
    'login.title': 'স্বাগতম',
    'login.subtitle': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'login.email': 'ইমেইল',
    'login.password': 'পাসওয়ার্ড',
    'login.remember': 'আমাকে মনে রাখুন',
    'login.forgot': 'পাসওয়ার্ড ভুলে গেছেন?',
    'login.signin': 'সাইন ইন',
    'login.signup': 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'login.demo': 'ডেমো অ্যাকাউন্ট',
    'login.admin': 'অ্যাডমিন লগইন',
    'login.moderator': 'মডারেটর লগইন',
    'login.user': 'ইউজার লগইন',
    'login.error': 'ভুল ইমেইল বা পাসওয়ার্ড',
    'login.success': 'লগইন সফল',
    
    // Profile
    'profile.personal.info': 'ব্যক্তিগত তথ্য',
    'profile.edit': 'প্রোফাইল সম্পাদনা',
    'profile.name': 'নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন',
    'profile.address': 'ঠিকানা',
    'profile.not.provided': 'প্রদান করা হয়নি',
    'profile.account.info': 'অ্যাকাউন্টের তথ্য',
    'profile.join.date': 'যোগদানের তারিখ',
    'profile.last.login': 'শেষ লগইন',
    'profile.update.success.title': 'প্রোফাইল আপডেট',
    'profile.update.success.message': 'আপনার প্রোফাইল সফলভাবে আপডেট হয়েছে।',
    'profile.login.required': 'লগইন প্রয়োজন',
    'profile.login.message': 'আপনার প্রোফাইল অ্যাক্সেস করতে লগইন করুন।',
    
    // Dashboard
    'dashboard.welcome': 'স্বাগতম',
    'dashboard.welcome.message': 'এখানে আপনার কমিউনিটি ড্যাশবোর্ডের একটি সংক্ষিপ্ত বিবরণ।',
    'dashboard.stats.total.users': 'মোট ব্যবহারকারী',
    'dashboard.stats.active.users': 'সক্রিয় ব্যবহারকারী',
    'dashboard.stats.recent.logins': 'সাম্প্রতিক লগইন',
    'dashboard.stats.administrators': 'প্রশাসক',
    'dashboard.role.distribution': 'ভূমিকা বিতরণ',
    'dashboard.quick.actions': 'দ্রুত কার্যক্রম',
    'dashboard.action.manage.users': 'ব্যবহারকারী পরিচালনা',
    'dashboard.action.view.activity': 'কার্যক্রম দেখুন',
    'dashboard.action.security.settings': 'নিরাপত্তা সেটিংস',
    'dashboard.login.required': 'ড্যাশবোর্ড অ্যাক্সেস প্রয়োজন',
    'dashboard.login.message': 'ড্যাশবোর্ড অ্যাক্সেস করতে লগইন করুন।',
    
    // Admin
    'admin.user.management': 'ব্যবহারকারী পরিচালনা',
    'admin.create.user': 'ব্যবহারকারী তৈরি',
    'admin.search.users': 'ব্যবহারকারী খুঁজুন...',
    'admin.all.roles': 'সকল ভূমিকা',
    'admin.role.admin': 'অ্যাডমিন',
    'admin.role.moderator': 'মডারেটর',
    'admin.role.user': 'ব্যবহারকারী',
    'admin.create.new.user': 'নতুন ব্যবহারকারী তৈরি',
    'admin.table.user': 'ব্যবহারকারী',
    'admin.table.role': 'ভূমিকা',
    'admin.table.status': 'অবস্থা',
    'admin.table.last.login': 'শেষ লগইন',
    'admin.table.actions': 'কার্যক্রম',
    'admin.status.active': 'সক্রিয়',
    'admin.status.inactive': 'নিষ্ক্রিয়',
    'admin.error': 'ত্রুটি',
    'admin.success': 'সফল',
    'admin.fill.required.fields': 'দয়া করে সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
    'admin.user.created.successfully': 'ব্যবহারকারী সফলভাবে তৈরি হয়েছে।',
    'admin.user.updated.successfully': 'ব্যবহারকারী সফলভাবে আপডেট হয়েছে।',
    'admin.user.deleted.successfully': 'ব্যবহারকারী সফলভাবে মুছে ফেলা হয়েছে।',
    'admin.cannot.delete.yourself': 'আপনি নিজের অ্যাকাউন্ট মুছতে পারবেন না।',
    'admin.access.denied': 'অ্যাক্সেস অস্বীকৃত',
    'admin.insufficient.permissions': 'এই পৃষ্ঠা অ্যাক্সেস করার জন্য আপনার পর্যাপ্ত অনুমতি নেই।',
    'admin.login.required': 'অ্যাডমিন অ্যাক্সেস প্রয়োজন',
    'admin.login.message': 'প্রশাসনিক অ্যাক্সেসের জন্য অ্যাডমিন সুবিধা সহ লগইন করুন।',
    
    // Registration
    'registration.step1.title': 'ফোন ও নিরাপত্তা',
    'registration.step1.subtitle': 'আপনার ফোন নম্বর যাচাই করুন এবং নিরাপত্তা সেট আপ করুন',
    'registration.step2.title': 'ব্যক্তিগত তথ্য',
    'registration.step2.subtitle': 'আপনার সম্পর্কে আমাদের বলুন',
    'registration.step3.title': 'ঠিকানার তথ্য',
    'registration.step3.subtitle': 'আপনি কোথায় অবস্থিত?',
    'registration.step4.title': 'পেশাগত তথ্য',
    'registration.step4.subtitle': 'আপনার পেশাগত পটভূমি শেয়ার করুন',
    'registration.phone.number': 'ফোন নম্বর',
    'registration.send.otp': 'OTP পাঠান',
    'registration.enter.otp': 'OTP প্রবেশ করান',
    'registration.verify': 'যাচাই করুন',
    'registration.password': 'পাসওয়ার্ড',
    'registration.confirm.password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'registration.full.name': 'পূর্ণ নাম',
    'registration.nick.names': 'ডাক নাম',
    'registration.nick.name': 'ডাক নাম',
    'registration.add.nickname': 'ডাক নাম যোগ করুন',
    'registration.date.of.birth': 'জন্ম তারিখ',
    'registration.gender': 'লিঙ্গ',
    'registration.select.gender': 'লিঙ্গ নির্বাচন করুন',
    'registration.male': 'পুরুষ',
    'registration.female': 'মহিলা',
    'registration.other': 'অন্যান্য',
    'registration.religion': 'ধর্ম',
    'registration.select.religion': 'ধর্ম নির্বাচন করুন',
    'registration.islam': 'ইসলাম',
    'registration.hinduism': 'হিন্দু ধর্ম',
    'registration.christianity': 'খ্রিস্টান ধর্ম',
    'registration.buddhism': 'বৌদ্ধ ধর্ম',
    'registration.marital.status': 'বৈবাহিক অবস্থা',
    'registration.select.marital.status': 'বৈবাহিক অবস্থা নির্বাচন করুন',
    'registration.single': 'অবিবাহিত',
    'registration.married': 'বিবাহিত',
    'registration.divorced': 'তালাকপ্রাপ্ত',
    'registration.widowed': 'বিধবা',
    'registration.emails': 'ইমেইল ঠিকানা',
    'registration.email': 'ইমেইল',
    'registration.add.email': 'ইমেইল যোগ করুন',
    'registration.additional.phones': 'অতিরিক্ত ফোন নম্বর',
    'registration.add.phone': 'ফোন যোগ করুন',
    'registration.personal': 'ব্যক্তিগত',
    'registration.office': 'অফিস',
    'registration.present.address': 'বর্তমান ঠিকানা',
    'registration.permanent.address': 'স্থায়ী ঠিকানা',
    'registration.district': 'জেলা',
    'registration.select.district': 'জেলা নির্বাচন করুন',
    'registration.address.details': 'ঠিকানার বিস্তারিত',
    'registration.address.placeholder': 'গ্রাম, বাড়ি, রাস্তা...',
    'registration.profile.headline': 'প্রোফাইল শিরোনাম',
    'registration.profile.headline.placeholder': 'নিজের সম্পর্কে সংক্ষিপ্ত বিবরণ...',
    'registration.professional.experience': 'পেশাগত অভিজ্ঞতা',
    'registration.add.experience': 'অভিজ্ঞতা যোগ করুন',
    'registration.experience': 'অভিজ্ঞতা',
    'registration.job.title': 'পদবী',
    'registration.company': 'কোম্পানি/প্রতিষ্ঠান',
    'registration.start.date': 'শুরুর তারিখ',
    'registration.end.date': 'শেষের তারিখ',
    'registration.currently.working': 'আমি বর্তমানে এই পদে কাজ করছি',
    'registration.job.location': 'কাজের স্থান',
    'registration.job.description': 'কাজের বিবরণ',
    'registration.job.description.placeholder': 'আপনার ভূমিকা এবং দায়িত্ব বর্ণনা করুন...',
    'registration.next': 'পরবর্তী',
    'registration.previous': 'পূর্ববর্তী',
    'registration.save.profile': 'সংরক্ষণ ও প্রোফাইলে যান',
    'registration.error': 'নিবন্ধন ত্রুটি',
    'registration.complete.step1': 'দয়া করে ফোন যাচাইকরণ সম্পূর্ণ করুন এবং পাসওয়ার্ড সেট করুন।',
    'registration.password.mismatch': 'পাসওয়ার্ড মেলে না।',
    'registration.name.required': 'পূর্ণ নাম প্রয়োজন।',
    'registration.district.required': 'উভয় ঠিকানার জন্য জেলা নির্বাচন প্রয়োজন।',
    'registration.otp.sent': 'OTP পাঠানো হয়েছে',
    'registration.otp.message': 'আপনার ফোনে OTP পাঠানো হয়েছে। ডেমো OTP:',
    'registration.otp.verified': 'OTP যাচাই হয়েছে',
    'registration.otp.success': 'ফোন নম্বর সফলভাবে যাচাই হয়েছে।',
    'registration.otp.error': 'যাচাইকরণ ব্যর্থ',
    'registration.otp.invalid': 'ভুল OTP। আবার চেষ্টা করুন।',
    'registration.success': 'নিবন্ধন সফল',
    'registration.profile.created': 'আপনার প্রোফাইল সফলভাবে তৈরি হয়েছে।',
    'registration.title': 'আমাদের কমিউনিটিতে যোগ দিন'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('onnorokom_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('onnorokom_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bn' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      toggleLanguage,
      t
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
